### ISSUE TITLE
网络结构上的问题

### ISSUE THREAD

**Issue by kaka-ice** [Roywangj/PointGL#1]
大佬你好，我在梳理pointGL网络结构（直接debug该代码openpoints/backbone/pointgl.py）的时候发现了有几个问题，特地来向你求证一下：
1.第271行中（fps_idx = furthest_point_sample(xyz, xyz.shape[1]//self.reduce).long()）最远点采样的点数应该是self.reduce吧，如果是xyz.shape[1]//self.reduce的话，则每次最远点采样的点数是2，感觉不合理。
2.经过local graph pooling后输出的x的通道数和下一层中point embedding卷积操作的通道数不一致，比如经过stage1后得到的x_shape为(1,131,512),而stage2中embedding卷积的输入通道数要求为128，即应该输入的x_shape应该为（1,128,512）。

**Comment by Roywangj** [comment]
你好, @kaka-ice , 感谢
1. 采样点的个数是xyz.shape[1]//self.reduce， xyz.shape[1]是点云中点的数量N, 因此，每次最远点采样的点数为N/2, N/4, ..., 这里你可以打个断点看一下。
2. 这里也是一致的，你可以检查一下这一段代码，https://github.com/Roywangj/PointGL/blob/36bff2345d003f10df41fb0f180cdb3493fef41e/openpoints/models/backbone/pointgl.py#L376-L378

**Comment by kaka-ice** [comment]
你好，感谢大佬回复。
第一个问题中，调用函数PointsetGrouper(out_channel,anchor_points,kneighbor,self.use_xyz,normalize)，reduce接收的参数是anchor_points=anchor_points//reduce,即anchor_points的值为最远点采样后的值（N/2, N/4, ...,），如果再进行xyz.shape[1]//self.reduce，那么最远点采样的点数就变成2了。

上面是FPNET的实现过程。

**Comment by Roywangj** [comment]
你好， @kaka-ice ，你的理解是没有问题的，不过采样次数不是无限上涨的，以scanobjectnn为例，输入的N为1024，一共进行4次采样，最终采样的结果为1024/16=64，不会变为2。

**Comment by Roywangj** [comment]
你好， @kaka-ice ，我先关闭这个issues了哈，有问题你可以随时打开，欢迎使用！
